### PR TITLE
[WIP] Use boolean to check input dimensions ordering

### LINKED ISSUE #133: `dim_order` possible simplification
In BTK at several places, one needs to know where the channels are last or not.
This is done through the `dim_order` keyword, that takes as input either "NCHW" or "NHWC".

I'm old enough to recall that issue existed in the early days of `tensorflow` because the default ordering had changed from the one used in `theano`, one of TF precursors.
They solved it by adding a boolean keyword called `channels_last`. 

IMHO we should use that convention as well, because
1. it spells easily and no one has to refer to the doc to understand its meaning
2. the boolean nature makes it very appropriate for the binary choice it does.

The only reason not to switch would be if you guys had in mind a third or more possibility of ordering the data.

### PR DESCRIPTION
**Pull request by aboucaud**
This PR replaces the use of `dim_order="NCHW` with `channels_last=False` and `dim_order="NHWC` with `channels_last=True`.

Fixes #133

### CODE REVIEW

**Comment by ismael-mendoza** [comment]
Thanks @aboucaud for this PR. I pushed a change just now were I have a proposal of how to fix the issue you pointed out with the `measure_functions`. Please let me know what you think, I had to extend `btk.multiprocess` to accept `kwargs` which was the main change.

**Comment by aboucaud** [comment]
Well I had in mind (and forgot to mention it in the meantime) was to wait until the PR #125 was merged to add more commits regarding the issue and the changes implied in `measure.py`. 
That could also leave some room to update multiprocessing in a different PR since it's unrelated, although necessary.
 
Just want to avoid things colliding in the middle. With those changes it will now make either PR difficult to merge first because of the concurrent changes.

**Comment by ismael-mendoza** [comment]
I see, that makes sense. I think the conflict should be pretty small but I agree that there will be some - I can rollback the changes I added and put them in separate PR  (to be merged when #125 is merged)

**Comment by aboucaud** [comment]
I think it would be best, even for the sake of a clean history

**Comment by aboucaud** [comment]
Also your work on multiprocessing is more important than this small refactoring PR

**Review by ismael-mendoza — APPROVED** [review]
Ok, I reverted the changes and this looks good to me now @aboucaud so I'm merging

**Comment by aboucaud** [comment]
There was a misunderstanding. I might not have been clear enough in my explanation, sorry. 

I changed the PR name to _work in progress_ : [WIP] so that we could wait for PR #125 to be merged to `main`, then rebase and continue what you wanted to do. That way, there are no conflicts to be solved on either branch ; whereas now the #125 cannot be merged as it is.

**Comment by ismael-mendoza** [comment]
ah I see what you mean now sorry about the confusion - hopefully it should still be quite smooth to the rebasing since the two PRs I merged did not touch `metrics.py` (and this one only touched measure.py in a comment)

**Pull request merged**
