### PR TITLE
Run notebooks once a week in a separate workflow

### PR DESCRIPTION
**Pull request by ismael-mendoza**
This page was useful for how to setup the cron job: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule. 

I set the cron job to run every Monday at 7a EST but I'm open to suggestions on this

### CODE REVIEW

**Comment by ismael-mendoza** [comment]
@thuiop - I've been wandering about this for a while. Should we bother checking the output of the cells of the notebook and checking if they are the same? I think I would be satisfied with just checking if any of the cells failed.

**Comment by ismael-mendoza** [comment]
I would suggest this flag 

```
-nbval-lax, which runs notebooks and checks for errors, but only compares the outputs of cells with a #NBVAL_CHECK_OUTPUT marker comment.
```

if there is a output that is really important is the same then we can add that `#NBVAL_CHECK_OUTPUT` to that cell.

**Comment by ismael-mendoza** [comment]
I realized that if we want to check outputs are exactly the same that should be a test anyways so I removed the `sanitize.cfg` and switched to `pytest --nbval-lax notebooks`.

**Comment by thuiop** [comment]
> @thuiop - I've been wandering about this for a while. Should we bother checking the output of the cells of the notebook and checking if they are the same with `sanitize`? I think I would be satisfied with just checking if any of the cells failed to run.

I'm not sure. I agree that it may be sufficient ; checking the output value ensures that it is "exactly the same" as it should be, but I am not entirely sure this is useful.

**Comment by ismael-mendoza** [comment]
Thanks @thuiop I think if we really want to check a function outputs exactly the same output this is better off as a test. The only thing about notebooks is that there are images but those we need to look at them by eye anyways

**Comment by thuiop** [comment]
It looks good to me but actually I wonder whether this is not a bit too far. I think we should check that the notebooks are actually runnable before merging to main ; maybe there is a way so that it does not do it automatically but there is a button we can click on before merging.

**Comment by ismael-mendoza** [comment]
In my terminal I ran it w/ both `nbval` and `nbval-lax` and both of them pass so I think we should be ok ? 

Could you remind me why are the last 3 cells of `00-intro.ipynb` skipped ?

**Comment by ismael-mendoza** [comment]
> It looks good to me but actually I wonder whether this is not a bit too far. 

I understand the concern, if you think it is useful to check output is exactly the same (maybe you have some notebook/cell in mind?) we can revert this last change. 

In my experience a notebook not having exatly the same output is usually not a sign of an error (hopefully the tests would catch that!) like when we added the progress bar in your other PR. Incidentally, how would you fix this last error? Where it is ok that the notebook cell changed with the progress bar? Would you need to sanitize it away?

**Comment by ismael-mendoza** [comment]
I can also see having an alert once a week notifying us that a notebook cell changed (even if small) might be good to review so I'm open to keeping it

**Comment by ismael-mendoza** [comment]
After more thought and learning about `nbval` a bit more, I decided to keep the sanitize as is

**Comment by ismael-mendoza** [comment]
`nbval` passing in my terminal so I'm merging this now

**Pull request merged**
