### PR TITLE
Update galsim-hub generative model to TF2

### LINKED ISSUE #224: Run Galsim_Hub model in tensorflow 2.0
It appears that having tensorflow 1.0 as a dependency keeps giving us security warnings and comes with other problems (like compatibility with other newer packages). It would be nice if we could migrate the galsim_hub model to tensorflow 2.0 somehow - I think @aboucaud , @thuiop  had some ideas?

### PR DESCRIPTION
**Pull request by aboucaud**
This PR aims at incorporating the ensentials of galsim-hub generative model API while switching to the use of `tensorflow` 2.x

Fixes #224

### CODE REVIEW

**Comment by thuiop** [comment]
Shouldn't we look for integrating this into Galsim Hub directly instead of in BTK ?

**Comment by ismael-mendoza** [comment]
> So do we plan on merging this now, and change it later if we make modifications to galsim_hub directly ?

Yes, although I find it unlikely that we will want to modify galsim_hub directly

**Comment by ismael-mendoza** [comment]
> The coverage check should act as a warning but not be blocking. 👇🏼
For instance it does not take into account that the code is actually tested in the notebooks.

I agree, thanks for the suggestion

**Comment by ismael-mendoza** [comment]
Hi @aboucaud - based on our discussions during the sprint week perhaps the easiest thing would be if you could provide me the model that needs to be downloaded (or should we ask Francois for it? ) and I can find a way to add it to the github repo ? (probably git lfs but not downloading it everytime it's needed)

**Comment by ismael-mendoza** [comment]
Hi @aboucaud and @thuiop , as we discussed in the last meeting. We have decided to delay the implementation of tensorflow/galsim hub after the v1.0.0 release. I will close this PR but keep the branch open, feel free to work more on this whenever you have tim but there is no rush anymore.

**Pull request closed without merging**
