### PR TITLE
Add documentation for updated survey system

### PR DESCRIPTION
**Pull request by thuiop**

### CODE REVIEW

**Comment by thuiop** [comment]
I am currently rewriting the “custom_tutorial” notebook ; it used to explain how to create a new survey. Should I remove that and restrict to modifying existing surveys, as it is now more complex to create new ones from scratch ?

**Comment by ismael-mendoza** [comment]
Hi @thuiop I think what you ask is exactly what we were thinking in #291 - we can do this later and for now you can remove this from the notebook and just explain how to modify existing ones

**Comment by thuiop** [comment]
I believe it should be ready for review @ismael-mendoza

**Comment by ismael-mendoza** [comment]
will take a look later today, thanks @thuiop !

**Comment by ismael-mendoza** [comment]
<p>(same below, I think there is another cell where you do this)</p>

---

 <a href='https://app.reviewnb.com/LSSTDESC/BlendingToolKit/pull/294/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ismael-mendoza** [comment]
Thanks @thuiop this is looking good- I just had a small comment in one of the notebooks

**Comment by thuiop** [comment]
<p>Hmmm that's weird, I am pretty sure I actually did the reverse change somewhere. There may have been a rebase problem at some point.</p>

---

 <a href='https://app.reviewnb.com/LSSTDESC/BlendingToolKit/pull/294/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ismael-mendoza** [comment]
<p>thanks!</p>

---

 <a href='https://app.reviewnb.com/LSSTDESC/BlendingToolKit/pull/294/discussion/'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Comment by ismael-mendoza** [comment]
looks great, merging now

**Pull request merged**
